# Generated by Django 4.2.5 on 2023-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/thumbnail'),
        ),
    ]
